# template for server
app:
  host-url: http://localhost
spring:
  config:
    import: optional:file:./config/sensitive-props.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
#    username: jira
#    password: CodeGymJira
    username: ${sensitive.datasource.username} #jira
    password: ${sensitive.datasource.password} #CodeGymJira

